version: "3"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  server:
    container_name: server_container
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./packages/server/.env
    ports:
      - "8000:8000"
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  web:
    container_name: web_container
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
    depends_on:
      - server
    env_file:
      - ./packages/web/.env
    ports:
      - "3000:3000"
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  postgres:
